# Generated by Django 2.1.2 on 2018-10-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbricks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
