# Generated by Django 2.1.2 on 2018-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbricks', '0002_auto_20181028_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
