# Generated by Django 2.1.2 on 2018-10-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbricks', '0007_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='res',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
