# Generated by Django 2.1.2 on 2018-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbricks', '0011_reviews_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='owners_name',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.CharField(choices=[('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai')], default='Bangalore', max_length=20),
        ),
    ]
