# Generated by Django 2.1.2 on 2018-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbricks', '0013_auto_20181109_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('South Indian', 'South Indian'), ('North Indian', 'North Indian'), ('Veg Only', 'Veg Only')], default='Veg Only', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.CharField(choices=[('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai')], default='Bangalore', max_length=20),
        ),
    ]
